export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";
export const UPDATE_SEARCH_TEXT = "UPDATE_NEW_POST_TEXT";
export const DELETE_SUCCESS_STATUS = "DELETE_SUCCESS_STATUS";
